export const Schema = {
  SimpleResume: {
    personalDetails: {
      name: true,
      email: true,
      phone: true,
      linkedin: true,
      github: true,
      location: true,
      country: true,
    },
    summary: true,
    workExperience: {
      id: true,
      company: true,
      role: true,
      duration: true,
      description: true,
      bulletPoints: true,
      isBulletPoints: true,
    },
    education: {
      id: true,
      degree: true,
      institution: true,
      year: true,
      description: true,
      grade: true,
      location: true,
    },
    skills: {
      id: true,
      name: true,
    },
    projects: {
      id: true,
      title: true,
      link: true,
      description: true,
      bulletPoints: true,
      isBulletPoints: true,
    },
    achievements: {
      id: true,
      title: true,
      year: true,
      description: true,
      bulletPoints: true,
      isBulletPoints: true,
    },
    languages: {
      id: true,
      language: true,
      level: true,
    },
  },
};
